function []=input_list_check(myFunction,myNargin);
%object:	print warning/error messages related to 
%		changes in arguments lists (June 2011).
%inputs:	myFunction: name of the calling routine
%		myNargin: number of arguments passed to the calling routine

if strcmp(myFunction,'convert2gcmfaces')&myNargin~=1;
    warning('inputCheck:convert2gcmfaces',...
            ['As of june 2011, convert2gcmfaces.m expects only \n' ...
    '         one input argument. The others were dismissed.\n' ...
    '         Type ''help convert2gcmfaces'' for details.']);
end;

if strcmp(myFunction,'convert2array')&myNargin~=1;
    warning('inputCheck:convert2array',...
            ['As of june 2011, convert2array.m expects only \n' ...
    '         one input argument. The other ones are dismissed.\n' ...
    '         Type ''help convert2array'' for details.']);
end;

if strcmp(myFunction,'convert2pcol')&myNargin~=3;
    warning('inputCheck:convert2pcol',...
            ['As of june 2011, convert2pcol.m expects only \n' ...
    '         three input arguments. The other ones are dismissed.\n' ...
    '         Type ''help convert2pcol'' for details.']);
end;

if strcmp(myFunction,'plot_one_field')&myNargin>1;
    error('inputCheck:plot_one_field',...
    ['As of March 2015, plot_one_field.m is a \n' ...
     'function with 0 or 1 input argument. \n'...
     'Type ''help plot_one_field'' for details.\n']);
end;

if strcmp(myFunction,'plot_std_field')&myNargin>0;
    error('inputCheck:plot_std_field',...
    ['As of March 2015, plot_std_field.m is a \n' ...
     'function without input argument. \n'...
     'Type ''help plot_std_field'' for details.\n']);
end;

